// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SceneBuilderApi.Data;

#nullable disable

namespace SceneBuilderApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511042528_AddSceneNotes")]
    partial class AddSceneNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SceneBuilderApi.Models.Calendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseUnitDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BaseUnitInIntegers")
                        .HasColumnType("int");

                    b.Property<string>("BaseUnitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentDay")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UniverseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UniverseId");

                    b.HasIndex("UserId");

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.CalendarEra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalendarId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EndDay")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StartDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.ToTable("CalendarEras");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.CalendarSpecialDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AbsoluteDay")
                        .HasColumnType("int");

                    b.Property<int>("CalendarId")
                        .HasColumnType("int");

                    b.Property<int?>("DayOfYear")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Significance")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.ToTable("CalendarSpecialDates");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.CalendarUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalendarId")
                        .HasColumnType("int");

                    b.Property<int?>("CountPerParent")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentUnitId")
                        .HasColumnType("int");

                    b.Property<string>("PluralName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.HasIndex("ParentUnitId");

                    b.ToTable("CalendarUnits");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UniverseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EntityTypeId");

                    b.HasIndex("UniverseId");

                    b.HasIndex("UserId");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.EntityFieldRefValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("bit");

                    b.Property<int>("RefEntityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("FieldId");

                    b.HasIndex("RefEntityId");

                    b.ToTable("EntityFieldRefValues");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.EntityFieldValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("bit");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("bit");

                    b.Property<double?>("NumberValue")
                        .HasColumnType("float");

                    b.Property<string>("TextValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("FieldId");

                    b.ToTable("EntityFieldValues");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.EntityRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FromEntityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("bit");

                    b.Property<int>("RelationshipTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ToEntityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromEntityId");

                    b.HasIndex("RelationshipTypeId");

                    b.HasIndex("ToEntityId");

                    b.ToTable("EntityRelationships");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.EntityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EntityTypes");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.EntityTypeField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGmOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("RefEntityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EntityTypeId");

                    b.HasIndex("RefEntityTypeId");

                    b.ToTable("EntityTypeFields");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.RelationshipType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RelationshipTypes");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.Scene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.SceneNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SceneId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.HasIndex("UserId");

                    b.ToTable("SceneNotes");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.SceneUniverse", b =>
                {
                    b.Property<int>("SceneId")
                        .HasColumnType("int");

                    b.Property<int>("UniverseId")
                        .HasColumnType("int");

                    b.HasKey("SceneId", "UniverseId");

                    b.HasIndex("UniverseId");

                    b.ToTable("SceneUniverses");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.StoryUniverse", b =>
                {
                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.Property<int>("UniverseId")
                        .HasColumnType("int");

                    b.HasKey("StoryId", "UniverseId");

                    b.HasIndex("UniverseId");

                    b.ToTable("StoryUniverses");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.Universe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Universes");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.Calendar", b =>
                {
                    b.HasOne("SceneBuilderApi.Models.Universe", "Universe")
                        .WithMany("Calendars")
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SceneBuilderApi.Models.User", "User")
                        .WithMany("Calendars")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Universe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.CalendarEra", b =>
                {
                    b.HasOne("SceneBuilderApi.Models.Calendar", "Calendar")
                        .WithMany("Eras")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.CalendarSpecialDate", b =>
                {
                    b.HasOne("SceneBuilderApi.Models.Calendar", "Calendar")
                        .WithMany("SpecialDates")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.CalendarUnit", b =>
                {
                    b.HasOne("SceneBuilderApi.Models.Calendar", "Calendar")
                        .WithMany("Units")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SceneBuilderApi.Models.CalendarUnit", "ParentUnit")
                        .WithMany("ChildUnits")
                        .HasForeignKey("ParentUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Calendar");

                    b.Navigation("ParentUnit");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.Entity", b =>
                {
                    b.HasOne("SceneBuilderApi.Models.EntityType", "EntityType")
                        .WithMany("Entities")
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SceneBuilderApi.Models.Universe", "Universe")
                        .WithMany("Entities")
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SceneBuilderApi.Models.User", "User")
                        .WithMany("Entities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EntityType");

                    b.Navigation("Universe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.EntityFieldRefValue", b =>
                {
                    b.HasOne("SceneBuilderApi.Models.Entity", "Entity")
                        .WithMany("FieldRefValues")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SceneBuilderApi.Models.EntityTypeField", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SceneBuilderApi.Models.Entity", "RefEntity")
                        .WithMany()
                        .HasForeignKey("RefEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Field");

                    b.Navigation("RefEntity");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.EntityFieldValue", b =>
                {
                    b.HasOne("SceneBuilderApi.Models.Entity", "Entity")
                        .WithMany("FieldValues")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SceneBuilderApi.Models.EntityTypeField", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.EntityRelationship", b =>
                {
                    b.HasOne("SceneBuilderApi.Models.Entity", "FromEntity")
                        .WithMany("OutgoingRelationships")
                        .HasForeignKey("FromEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SceneBuilderApi.Models.RelationshipType", "RelationshipType")
                        .WithMany("Relationships")
                        .HasForeignKey("RelationshipTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SceneBuilderApi.Models.Entity", "ToEntity")
                        .WithMany("IncomingRelationships")
                        .HasForeignKey("ToEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromEntity");

                    b.Navigation("RelationshipType");

                    b.Navigation("ToEntity");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.EntityType", b =>
                {
                    b.HasOne("SceneBuilderApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.EntityTypeField", b =>
                {
                    b.HasOne("SceneBuilderApi.Models.EntityType", "EntityType")
                        .WithMany("Fields")
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SceneBuilderApi.Models.EntityType", "RefEntityType")
                        .WithMany()
                        .HasForeignKey("RefEntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EntityType");

                    b.Navigation("RefEntityType");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.RelationshipType", b =>
                {
                    b.HasOne("SceneBuilderApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.Scene", b =>
                {
                    b.HasOne("SceneBuilderApi.Models.Story", "Story")
                        .WithMany("Scenes")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.SceneNote", b =>
                {
                    b.HasOne("SceneBuilderApi.Models.Scene", "Scene")
                        .WithMany()
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SceneBuilderApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Scene");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.SceneUniverse", b =>
                {
                    b.HasOne("SceneBuilderApi.Models.Scene", "Scene")
                        .WithMany("SceneUniverses")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SceneBuilderApi.Models.Universe", "Universe")
                        .WithMany("SceneUniverses")
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Scene");

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.Story", b =>
                {
                    b.HasOne("SceneBuilderApi.Models.User", "User")
                        .WithMany("Stories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.StoryUniverse", b =>
                {
                    b.HasOne("SceneBuilderApi.Models.Story", "Story")
                        .WithMany("StoryUniverses")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SceneBuilderApi.Models.Universe", "Universe")
                        .WithMany("StoryUniverses")
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Story");

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.Universe", b =>
                {
                    b.HasOne("SceneBuilderApi.Models.User", "User")
                        .WithMany("Universes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.Calendar", b =>
                {
                    b.Navigation("Eras");

                    b.Navigation("SpecialDates");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.CalendarUnit", b =>
                {
                    b.Navigation("ChildUnits");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.Entity", b =>
                {
                    b.Navigation("FieldRefValues");

                    b.Navigation("FieldValues");

                    b.Navigation("IncomingRelationships");

                    b.Navigation("OutgoingRelationships");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.EntityType", b =>
                {
                    b.Navigation("Entities");

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.RelationshipType", b =>
                {
                    b.Navigation("Relationships");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.Scene", b =>
                {
                    b.Navigation("SceneUniverses");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.Story", b =>
                {
                    b.Navigation("Scenes");

                    b.Navigation("StoryUniverses");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.Universe", b =>
                {
                    b.Navigation("Calendars");

                    b.Navigation("Entities");

                    b.Navigation("SceneUniverses");

                    b.Navigation("StoryUniverses");
                });

            modelBuilder.Entity("SceneBuilderApi.Models.User", b =>
                {
                    b.Navigation("Calendars");

                    b.Navigation("Entities");

                    b.Navigation("Stories");

                    b.Navigation("Universes");
                });
#pragma warning restore 612, 618
        }
    }
}
